(******************************************************************************)
(*                                                                            *)
(*             Soundness Gap Under Algebraic Group Model Failure              *)
(*                                                                            *)
(*     PPT adversary with non-negligible advantage against a concrete         *)
(*     ZK authentication protocol when the algebraic group model does         *)
(*     not hold for the instantiated elliptic curve. Constructs an            *)
(*     explicit forgery strategy from AGM violation witnesses.                *)
(*                                                                            *)
(*     "Trust, but verify."                                                   *)
(*     – Russian proverb                                                      *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: March 20, 2026                                                   *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
